language: go
os:
  - linux
go:
  - "1.11"
install:
script: go get -t -v ./...
after_success:
  - go build -o blank-cron-linux-amd64 -ldflags "-X main.buildTime=`date +%Y-%m-%d:%H:%M:%S` -X main.gitHash=`git rev-parse --short HEAD`"
  - GOOS=darwin GOARCH=amd64 go build -o blank-cron-darwin-amd64 -ldflags "-X main.buildTime=`date +%Y-%m-%d:%H:%M:%S` -X main.gitHash=`git rev-parse --short HEAD`"
  - GOOS=windows GOARCH=amd64 go build -o blank-cron-win32-amd64.exe -ldflags "-X main.buildTime=`date +%Y-%m-%d:%H:%M:%S` -X main.gitHash=`git rev-parse --short HEAD`"

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - blank-cron-linux-amd64
    - blank-cron-darwin-amd64
    - blank-cron-win32-amd64.exe
  skip_cleanup: true
  on:
    tags: true
